import Foundation

struct ChovviBotanicalBrew: Codable, Hashable {
    let chovviBotanicalAcidity: String
    let chovviBotanicalAeropress: String
    let chovviBotanicalAftertaste: String
    let chovviBotanicalAroma: String
    let chovviBotanicalBatch: String
    let chovviBotanicalBloom: Int
    let chovviBotanicalBody: Int
    let chovviBotanicalBrewer: [String]
    let chovviBotanicalBurr: [String]
}

struct ChovviBrightBrew: Codable, Hashable {
    let chovviBrightAcidity: String
    let chovviBrightAeropress: String
    let chovviBrightAftertaste: String
    let chovviBrightAroma: String
    let chovviBrightBatch: Int
    let chovviBrightBloom: String
    let chovviBrightBody: [String]
    let chovviBrightBrewer: [String]
}

struct ChovviCaramelBrew: Codable, Hashable {
    let chovviCaramelAcidity: String
    let chovviCaramelAeropress: String
    let chovviCaramelAftertaste: [String]
    let chovviCaramelAroma: String
    let chovviCaramelBatch: Int
    let chovviCaramelBloom: Int
    let chovviCaramelBody: String
    let chovviCaramelBrewer: [String]
    let chovviCaramelBurr: [String]
}

struct ChovviCeramicBrew: Codable, Hashable {
    let chovviCeramicAcidity: String
    let chovviCeramicAeropress: String
    let chovviCeramicAftertaste: String
    let chovviCeramicAroma: String
    let chovviCeramicBatch: Int
    let chovviCeramicBloom: Int
    let chovviCeramicBody: String
    let chovviCeramicBrewer: [String]
}

struct ChovviSilkyBrew: Codable, Hashable {
    let chovviSilkyAcidity: String
    let chovviSilkyAeropress: String
    let chovviSilkyAftertaste: String
    let chovviSilkyAroma: String
    let chovviSilkyBatch: Int
    let chovviSilkyBloom: Int
    let chovviSilkyBrewer: String
    let chovviSilkyBurr: String
}

enum ChovviCitrusBrew {
    static let roastArchiveLabel = [
        String.chovviUnmask("cChjoDvAvii9GuoklvdkePnuACcIi1dfiJtZyL"),
        String.chovviUnmask("cQhuoJvIvCizGRowlrdReAnCAte8rBoNprrYeLsosj"),
        String.chovviUnmask("cYhioavGvVi0Gzo5lvd2eWnmAmfEtyeMrItTaVsgtSeH"),
        String.chovviUnmask("c2h4o1v7vKipGzoKlOdVe5n6AXrcoYmAaP")
    ]

    static func roastArchiveCard(_ roastArchiveRecord: String) -> String {
        let roastArchiveItem = [
            "⭐️": String.chovviUnmask("chhToRvEv4ixGxoHl0d7eQn4ALcDikdbiat5ye"),
            "✨": String.chovviUnmask("cyhIoYvrvQilGooqlLdGeRnCAVeprNo1pBr2eDs2sF"),
            "🌤️": String.chovviUnmask("cmhSo0vxvliFGuosladreRnUADfXtzeSrqt1awsJtmex"),
            "☕️": String.chovviUnmask("cSh9oIvFvNiPGuokl3dzeLnGA6rSoJmLaW"),
            "🌿": String.chovviUnmask("cThBoVv3vFiJGEoHlNdSelnoA1cuizdZiIt9yf"),
            "🌸": String.chovviUnmask("cNhNoUvdvYi6GjonlvdoePn3A0enr2obpQrQe9susD"),
            "🥐": String.chovviUnmask("cnh3oQvLveibGeoDlcdAeonwAXrEoXmiaU")
        ]
        return roastArchiveItem[roastArchiveRecord] ?? roastArchiveRecord
    }

    static var roastArchiveSection: [ChovviSilkyBrew] {
        guard
            let roastArchivePreview = UserDefaults.standard.data(forKey: String.chovviUnmask("cThpo2vnviiMGDrCaDntuwluaYrVTReMx1tGuSrReP")),
            let roastArchiveTrigger = try? JSONDecoder().decode([ChovviSilkyBrew].self, from: roastArchivePreview)
        else { return [] }
        return roastArchiveTrigger
    }

    static var roastArchivePreview: [ChovviCaramelBrew] {
        guard
            let roastArchiveTrigger = UserDefaults.standard.data(forKey: String.chovviUnmask("c2h7o1vbvxiUSop6eTcCiaa7ljtMyvTBeVxdtfuPrOez")),
            let roastArchiveLayout = try? JSONDecoder().decode([ChovviCaramelBrew].self, from: roastArchiveTrigger)
        else { return [] }
        return roastArchiveLayout
    }

    static let roastArchiveCanvas: [ChovviBotanicalBrew] = [
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("czhEoEvSvIiy-nuLsOe3ry-q0j1c"), chovviBotanicalAeropress: "Maya Chen", chovviBotanicalAftertaste: "@mayabrews", chovviBotanicalAroma: "chovviAromaticAcidity", chovviBotanicalBatch: "Slow mornings, floral beans, and window-side cups.", chovviBotanicalBloom: 1280, chovviBotanicalBody: 386, chovviBotanicalBrewer: [String.chovviUnmask("cqhUoSvqvgiR-NrFopo7mp-U0W10"), String.chovviUnmask("cLhEoSv3vBiT-SrHoqo5mv-90U5o")], chovviBotanicalBurr: [String.chovviUnmask("cThno8v2vtig-guEsaeUrQ-D0y2l"), String.chovviUnmask("c2hHoMvgvkiN-cuKsBeVr9-Y0o4K"), String.chovviUnmask("cyhfoSvMvKiQ-1u7steKrR-50G8K")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cshWobv9vIiF-auMsZekrX-H082i"), chovviBotanicalAeropress: "Noah Reed", chovviBotanicalAftertaste: "@noahpours", chovviBotanicalAroma: "chovviAromaticAeropress", chovviBotanicalBatch: "Espresso notes and careful dial-ins every morning.", chovviBotanicalBloom: 942, chovviBotanicalBody: 214, chovviBotanicalBrewer: [String.chovviUnmask("c3hmofvYv5i8-rrno8oJmj-e0V2o"), String.chovviUnmask("cdhjodvMvuic-Erqodo2m6-00F6s")], chovviBotanicalBurr: [String.chovviUnmask("clhAo7vav3iB-LupsueIrC-Q0M1d"), String.chovviUnmask("cghyo7vEvDiv-OuVsXeDrO-10m6T")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cRhroGvfvJic-8uXsieWrQ-H0k35"), chovviBotanicalAeropress: "Sofia Lane", chovviBotanicalAftertaste: "@sofialatte", chovviBotanicalAroma: "chovviAromaticAftertaste", chovviBotanicalBatch: "Latte art, ceramic cups, and calm café corners.", chovviBotanicalBloom: 1765, chovviBotanicalBody: 431, chovviBotanicalBrewer: [String.chovviUnmask("cVhzoGvGveiF-dr8o6otmH-B0Y39")], chovviBotanicalBurr: [String.chovviUnmask("cLhwoyvnvhim-tu8sgeXrR-d031R"), String.chovviUnmask("cFhOoCvNv4iP-ju6szeorA-M0s5P"), String.chovviUnmask("cnhZoBv7vniz-5uEsQeUrz-G0c9W")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cvhko5v5vri8-yups5eUrg-U0A4b"), chovviBotanicalAeropress: "Ethan Cole", chovviBotanicalAftertaste: "@ethanroasts", chovviBotanicalAroma: "chovviAromaticAroma", chovviBotanicalBatch: String.chovviUnmask("LCeua4rcnficnRgI Se0vze3rTyB arco1aosyti Xc8unrxvUe2 4o8nHeV QbCaXtPc3hS cawt3 zao 5tyiWmseQ.X"), chovviBotanicalBloom: 823, chovviBotanicalBody: 198, chovviBotanicalBrewer: [String.chovviUnmask("cfhAo2vevCiE-qrqo5odmf-I0z1T"), String.chovviUnmask("cih1o6vBvUir-erQoZorm6-90b2d")], chovviBotanicalBurr: [String.chovviUnmask("cVhUoqvTvpiP-KuVsiewr8-I0M29"), String.chovviUnmask("c4hEovvyv8iy-UuAs5eirT-d150p")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cnhEofvtvtiH-4uBsVeJrh-O0h5S"), chovviBotanicalAeropress: "Ava Brooks", chovviBotanicalAftertaste: "@avacafes", chovviBotanicalAroma: "chovviAromaticBatch", chovviBotanicalBatch: "Finding warm cafés and thoughtful seasonal menus.", chovviBotanicalBloom: 2110, chovviBotanicalBody: 604, chovviBotanicalBrewer: [String.chovviUnmask("cihboCvZvciF-ZrKoqo2mD-W0x4e")], chovviBotanicalBurr: [String.chovviUnmask("c2hFouvxvyig-fu2s6eDrQ-E0l3q"), String.chovviUnmask("c0hvofvPvuiB-Euaseeurc-B1A1Z"), String.chovviUnmask("ckhDo3vSvji2-zuFs4e3rS-c1m5U")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("coh7oQvhvriP-1uLsleNr2-n0i6v"), chovviBotanicalAeropress: "Leo Martin", chovviBotanicalAftertaste: "@leogrinds", chovviBotanicalAroma: "chovviAromaticBloom", chovviBotanicalBatch: String.chovviUnmask("H6aznvds agLrSiknRdVeAr0sn,Q qc6lieaadnY 5fmiAlutYe2rxsL,1 WaEnkd3 kbmrfi2gmhFtL qckuMpvsg.g"), chovviBotanicalBloom: 734, chovviBotanicalBody: 176, chovviBotanicalBrewer: [String.chovviUnmask("c1h7o9vIvSi6-srxo4oEmG-X0S2B"), String.chovviUnmask("ckhpoUvTvfia-KrmoSovml-c0v6X")], chovviBotanicalBurr: [String.chovviUnmask("cghDo8v3vpiG-2uZsvegr2-k0o2D"), String.chovviUnmask("cyhVodv6v3iO-kuKsKeFrk-U1I2I")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("clhToOvBvMix-Eu6s7eKrf-C0y7v"), chovviBotanicalAeropress: "Emma Hart", chovviBotanicalAftertaste: "@emmareads", chovviBotanicalAroma: "chovviAromaticBody", chovviBotanicalBatch: "Books, soft chairs, and coffee with long finishes.", chovviBotanicalBloom: 1496, chovviBotanicalBody: 352, chovviBotanicalBrewer: [String.chovviUnmask("cTh2ofvWvTiQ-qr6oxoQmi-R0S5Q")], chovviBotanicalBurr: [String.chovviUnmask("c8hYovvcvTi0-5ufs4errE-90X1D"), String.chovviUnmask("cphxoGv7vzih-KuRsWeTrO-e1G4V")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cUhqokvsv1iW-Buhsee2rj-q0d8X"), chovviBotanicalAeropress: "Liam Stone", chovviBotanicalAftertaste: String.chovviUnmask("@NleiCazmLfaialAtxekrX"), chovviBotanicalAroma: "chovviAromaticBrewer", chovviBotanicalBatch: "Weekend brews with precise ratios and gentle pours.", chovviBotanicalBloom: 1087, chovviBotanicalBody: 267, chovviBotanicalBrewer: [String.chovviUnmask("cyh7ouvMvFib-5r7oWoCmo-u0D1z"), String.chovviUnmask("cYhaoYvOv4iK-Grho1oWmC-80q6X")], chovviBotanicalBurr: [String.chovviUnmask("cah4oAv4vWi8-muksheord-d0g1f"), String.chovviUnmask("cAhrouv1vfiN-YuKsEeora-J0v6y"), String.chovviUnmask("coh0oVvmvqiu-luosQeJr2-61p6h")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cThIo0v1v5iJ-SufsFerr8-y0K9G"), chovviBotanicalAeropress: "Isla Moore", chovviBotanicalAftertaste: "@islafoam", chovviBotanicalAroma: "chovviAromaticBurr", chovviBotanicalBatch: String.chovviUnmask("PorMamc4tKi7cFiTnJgF atcuqlQiLpEsl,3 qhQeJavr7twsP,a QaDnfdi fsHi8likIyG wtkevxUtwunrCejse.1"), chovviBotanicalBloom: 2318, chovviBotanicalBody: 718, chovviBotanicalBrewer: [String.chovviUnmask("cGhDorvavtiX-kraoHohm9-L0l3K")], chovviBotanicalBurr: [String.chovviUnmask("czhyoDvivyi3-KuDsYearJ-Q0N3B"), String.chovviUnmask("c9h6ofvgvCik-3uTs8eMrA-S1N70")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("c8hNolvwvCiv-cuksme8rd-i1b0Q"), chovviBotanicalAeropress: "Owen Park", chovviBotanicalAftertaste: "@owenorigin", chovviBotanicalAroma: "chovviAromaticCafe", chovviBotanicalBatch: "Origin stories, harvest notes, and careful cupping.", chovviBotanicalBloom: 675, chovviBotanicalBody: 143, chovviBotanicalBrewer: [String.chovviUnmask("c9hqoMvRvRiV-NrvosoFmW-G072o")], chovviBotanicalBurr: [String.chovviUnmask("cjh8o3vrvuiD-uuLskeBrZ-20e40"), String.chovviUnmask("cfhMoRvAvLi1-SuosIeHr7-d1R8V")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cah3oZvCvNiP-futsvedry-P1k1E"), chovviBotanicalAeropress: "Mila Hayes", chovviBotanicalAftertaste: "@milacorners", chovviBotanicalAroma: "chovviAromaticCalibration", chovviBotanicalBatch: "Quiet interiors, wooden tables, and soft light.", chovviBotanicalBloom: 1934, chovviBotanicalBody: 522, chovviBotanicalBrewer: [String.chovviUnmask("cXhOosvPvFi2-xrCoxoSmy-M0i4C")], chovviBotanicalBurr: [String.chovviUnmask("cxh0oWvdvTil-5u3siegrP-v0X5E"), String.chovviUnmask("cwh6oZvnv3iG-zuQsceDrz-r169B")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cmhHomvOvWin-9ucsReMrN-y1v2m"), chovviBotanicalAeropress: "Lucas Gray", chovviBotanicalAftertaste: "@lucaskettle", chovviBotanicalAroma: "chovviAromaticCascade", chovviBotanicalBatch: "Thermal control and repeatable home recipes.", chovviBotanicalBloom: 887, chovviBotanicalBody: 229, chovviBotanicalBrewer: [String.chovviUnmask("c4hZoLvMvfi1-lrnowoXmr-2036p")], chovviBotanicalBurr: [String.chovviUnmask("cthuocvJvXi9-ruhslearp-l016Y"), String.chovviUnmask("cthloKv9vnit-GuisMexrl-U2G0z")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("csh4oFvwv5iZ-ouwseeTre-O1n3g"), chovviBotanicalAeropress: "Nora Bell", chovviBotanicalAftertaste: "@noracocoa", chovviBotanicalAroma: "chovviAromaticChamber", chovviBotanicalBatch: String.chovviUnmask("Cto5c8oSaC Msnw9eFe3tqnYeCs1sC NaYnidI zcholm5fRoerQtTiTnQgl IbmrdeWaXk7fSaVsNtl Qpha6iHr1iNn0g3s7.j"), chovviBotanicalBloom: 1254, chovviBotanicalBody: 314, chovviBotanicalBrewer: [String.chovviUnmask("cmhXo9vAvYiL-GrloKoCmy-t0W1L"), String.chovviUnmask("cThkoYvsvPi5-jrJoOoTm7-W0M5s")], chovviBotanicalBurr: [String.chovviUnmask("cih5oLvtvGiD-3uqsyeJrW-30b7D"), String.chovviUnmask("cThzo4vWv3if-pu8sWe6r1-M1f54")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("c8hxo4vVvhiK-juSsae4rH-W184g"), chovviBotanicalAeropress: "Henry Ross", chovviBotanicalAftertaste: "@henrypages", chovviBotanicalAroma: "chovviAromaticClarity", chovviBotanicalBatch: "A fresh chapter and a carefully brewed cup.", chovviBotanicalBloom: 1012, chovviBotanicalBody: 287, chovviBotanicalBrewer: [String.chovviUnmask("cYhLo1vtvti8-prEo4oOm1-e0y5F")], chovviBotanicalBurr: [String.chovviUnmask("cChpokvOvKiT-tutsNeErm-40j7q"), String.chovviUnmask("cMhVoTvQvQi8-puVseeCr0-q1y6D")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cihiovvGv8iP-6uQsLeJrf-H1D5S"), chovviBotanicalAeropress: "Chloe King", chovviBotanicalAftertaste: "@chloebrunch", chovviBotanicalAroma: "chovviAromaticExtraction", chovviBotanicalBatch: "Croissants, fruit, and bright morning tables.", chovviBotanicalBloom: 1586, chovviBotanicalBody: 409, chovviBotanicalBrewer: [String.chovviUnmask("coh9oSvSvNiN-Zrdoqoqml-M0b1y"), String.chovviUnmask("c8hJoZvSvri1-Mr6oJoXmP-n0H4I")], chovviBotanicalBurr: [String.chovviUnmask("cbhSosvfvuiD-6uZsyehrp-X0f5f"), String.chovviUnmask("cuhpoGvLvRiE-kuis9esre-F1Z3o")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cohToDvTviir-DuysIeHr0-X1V6v"), chovviBotanicalAeropress: "Jack Wells", chovviBotanicalAftertaste: "@jackbrewbar", chovviBotanicalAroma: "chovviAromaticFermentation", chovviBotanicalBatch: "Building a practical coffee corner at home.", chovviBotanicalBloom: 764, chovviBotanicalBody: 192, chovviBotanicalBrewer: [String.chovviUnmask("cBhSoMvuvliD-6rZo5ormC-K0w6x")], chovviBotanicalBurr: [String.chovviUnmask("cRhLoEvavhik-4uIscekr6-M0S8d"), String.chovviUnmask("cIhNo9v9vkiX-auOsSeHrj-31F4H")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("c6h8opv1vjiy-6uosOeJrs-P1u7Z"), chovviBotanicalAeropress: "Grace Lin", chovviBotanicalAftertaste: "@gracecrema", chovviBotanicalAroma: String.chovviUnmask("cihXozvcv1iEArrSodmsamtjikcmF4i7l4tNeMrW"), chovviBotanicalBatch: "Crema, café sketches, and small daily rituals.", chovviBotanicalBloom: 2043, chovviBotanicalBody: 571, chovviBotanicalBrewer: [String.chovviUnmask("cmhIoPvbvwiK-crBoBormA-U0u3D"), String.chovviUnmask("cbh1oUvivGiP-YrvoJowm6-g0H4h")], chovviBotanicalBurr: [String.chovviUnmask("cPhyoSvmv6io-Uu9sAehrN-b0K9b"), String.chovviUnmask("cWh2oTvIvYiy-IuasJebrd-k1Y96")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cOhDouvcvBip-ou4seetrU-h1m8S"), chovviBotanicalAeropress: "Finn Young", chovviBotanicalAftertaste: "@finnbeans", chovviBotanicalAroma: "chovviAromaticGrinder", chovviBotanicalBatch: "Comparing varietals and writing simple tasting notes.", chovviBotanicalBloom: 698, chovviBotanicalBody: 158, chovviBotanicalBrewer: [String.chovviUnmask("cbhLoSvBvoiD-hryohocmZ-2052w")], chovviBotanicalBurr: [String.chovviUnmask("cMhooDvOv5iI-Nuasle4r8-n1M0C"), String.chovviUnmask("cMh4oPvMvOiz-eu6sjeBr1-j2O0z")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cMhDokvtvui7-OuLsOe3rS-W1B9c"), chovviBotanicalAeropress: "Ruby Scott", chovviBotanicalAftertaste: "@rubytable", chovviBotanicalAroma: "chovviAromaticInfusion", chovviBotanicalBatch: "Seasonal cups and welcoming neighborhood cafés.", chovviBotanicalBloom: 1378, chovviBotanicalBody: 365, chovviBotanicalBrewer: [String.chovviUnmask("cghOofvNvciB-HrtoSolmM-W0a4y")], chovviBotanicalBurr: [String.chovviUnmask("cvhpotvQvaiu-pugsle3rE-r1z1h"), String.chovviUnmask("cXhzoevAvmih-4u0sMeHrT-01x7d")]),
        ChovviBotanicalBrew(chovviBotanicalAcidity: String.chovviUnmask("cOhTopvNvhio-DuUsIeyrR-n2S0r"), chovviBotanicalAeropress: "Theo Grant", chovviBotanicalAftertaste: "@theobloom", chovviBotanicalAroma: "chovviAromaticKettle", chovviBotanicalBatch: "Fresh bloom, clean water, and patient extraction.", chovviBotanicalBloom: 913, chovviBotanicalBody: 241, chovviBotanicalBrewer: [String.chovviUnmask("cphmohvqvkiR-6rsoBo2mR-l0i1a"), String.chovviUnmask("cYheoNvuvTia-irUoGoJmJ-O0160")], chovviBotanicalBurr: [String.chovviUnmask("cvhBoSvPvQiT-9uasVeNrE-J1Q20"), String.chovviUnmask("cAhloPvOvOi3-Iuqszegrh-K1D8z")])
    ]

    static let roastArchiveScroll: [ChovviBrightBrew] = [
        ChovviBrightBrew(chovviBrightAcidity: String.chovviUnmask("cZhtoGv1vUia-Mr0oyoZmE-V091P"), chovviBrightAeropress: String.chovviUnmask("MwoXrnnti9nagm LBQrJe2wE tCbluukb9"), chovviBrightAftertaste: String.chovviUnmask("STtpaUrJtp 5yBoFu0rO Sdyawyz IwqiItWhI Ifrreecs1hP WcMoafIfweLeZ,R LckoLzqyU UcvoMnxvEeQrZsna0tNikopn4sb,N vainWd4 Qplods5ilt3iWvDed xvSiOb7eIs7.S"), chovviBrightAroma: "chovviArtisanAcidity", chovviBrightBatch: 87, chovviBrightBloom: String.chovviUnmask("c4hNo1vLv7iu-YupsHe2rX-Q0H1K"), chovviBrightBody: [String.chovviUnmask("cRhmorv4vDiT-KuVsKe6rR-z0h1v"), String.chovviUnmask("c5hBoevwvgiR-ZuespeLrV-B0C4N"), String.chovviUnmask("cShboYvrv2i6-Qu5sSeVrz-40F8P"), String.chovviUnmask("cQhNomvzvXi8-3u8soe1rU-l1X3N"), String.chovviUnmask("cIhTo2v4vHiW-Yuqsle2rR-l155i"), String.chovviUnmask("cbh7oAvhvDiq-ruqsie3rD-Z2z06")], chovviBrightBrewer: [String.chovviUnmask("cBhjotvHvniM-ApLo6sMtc-q081h"), String.chovviUnmask("cGhPoavbvtib-4c7lTizp2-L011I")]),
        ChovviBrightBrew(chovviBrightAcidity: String.chovviUnmask("cThXokvevqiH-PrhovoCm2-V0A2n"), chovviBrightAeropress: String.chovviUnmask("E0sApqrPe9sCsNoP uTtamlpkl"), chovviBrightAftertaste: String.chovviUnmask("An gpjlCaWc6er 8fMo2rT sexs7pjrReys2sGoI MfNaJngsr 1tio5 IehxIcVhva6ntgNex QbSr1ecwKiPnPg0 utFiYp9sp ba8nFdn 8d3afi3lLyA ZcnomfDf5eReR Asztso1rXiSeYsP.H"), chovviBrightAroma: "chovviArtisanAeropress", chovviBrightBatch: 134, chovviBrightBloom: String.chovviUnmask("c5h9oMvivpi9-1uBsaevrV-O0T2t"), chovviBrightBody: [String.chovviUnmask("c5hboCvTvdiY-vuZs6eFrx-R0x2J"), String.chovviUnmask("clh4owvQv6ik-ouRs7eVrY-V0n4D"), String.chovviUnmask("cEh9o1vTvFiI-buIsJe3rf-r0Z6V"), String.chovviUnmask("cAh3oMvgvBiO-ouVsie0rC-h190r"), String.chovviUnmask("cFh4oXvQv0iD-pu8s7eHrT-k1h8O")], chovviBrightBrewer: [String.chovviUnmask("cyhqoZvLv9ip-ApBoRsptM-p0Y24"), String.chovviUnmask("cbhFoSvAveiE-VcFlqikp5-20D2F")]),
        ChovviBrightBrew(chovviBrightAcidity: String.chovviUnmask("cmhHovvGvXi5-drgoKo7mX-z0W32"), chovviBrightAeropress: "Latte", chovviBrightAftertaste: String.chovviUnmask("SGhHajr9eM AbueIaXu2tiipfFutla XlSa8t1tEet CaXretr,Q jcCa4fKér bdAiksuc7ovvKenrki6e6sS,t jaMnedZ VyvoLuDrL yfaadv5osrki0tWeC dceoOf1fPe8et Gm5oMmCegnHtKsJ.f"), chovviBrightAroma: "chovviArtisanAftertaste", chovviBrightBatch: 62, chovviBrightBloom: String.chovviUnmask("cyh1oRv8vyiC-Lu1szegrF-l0p3P"), chovviBrightBody: [String.chovviUnmask("cPhAowvpvri7-hu1sPezrc-z0s3q"), String.chovviUnmask("cVh5oCvFvciw-HudsDeKrg-h089d"), String.chovviUnmask("cYh8oWvsvUiR-MuCs3eKrp-B177A")], chovviBrightBrewer: [String.chovviUnmask("c7hNoGv0vuiV-1paoIsatj-90k2P"), String.chovviUnmask("cThroEvgvQi8-ic3lDiXp7-J0831")]),
        ChovviBrightBrew(chovviBrightAcidity: String.chovviUnmask("cqhUozvevDiI-ir9oJoGm2-P0o48"), chovviBrightAeropress: "Café Hopping", chovviBrightAftertaste: String.chovviUnmask("DdiKs7caofv4eBrp xheiSdgdtelnb 6c1aefté0sq,v lrdeZvsire4wk xyioruorI mf0a8vGodreiTtye9sB,Z waFntdC JiPnZsrpxikr8eL tyLoPucrh 9nkeLx2tG Kv6iosEiPtr.T"), chovviBrightAroma: "chovviArtisanBatch", chovviBrightBatch: 176, chovviBrightBloom: String.chovviUnmask("cFhLoEvYvYi9-yuxsze4rf-O0Q5B"), chovviBrightBody: [String.chovviUnmask("cFhwoOvsv5in-9upsZefr5-00j5g"), String.chovviUnmask("c8h9otvzvEi9-fuTsielrX-41J10"), String.chovviUnmask("cthpo0v2vFiL-iuSs3eur9-j185Y"), String.chovviUnmask("cShLoOvMvbi3-6ucseehrI-J137Y"), String.chovviUnmask("chh8o1v4vniI-UuYsLeuri-L1B9N")], chovviBrightBrewer: [String.chovviUnmask("cGh2oHvzv9in-Ppmogs5tV-c0F3U"), String.chovviUnmask("cthLozvKvdie-lceljiwpo-b0o4I")]),
        ChovviBrightBrew(chovviBrightAcidity: String.chovviUnmask("c2h0odvXvfia-0r1otoUm1-b0n5W"), chovviBrightAeropress: "Coffee & Books", chovviBrightAftertaste: "Slow down with a good book and your favorite cup of coffee.", chovviBrightAroma: "chovviArtisanAroma", chovviBrightBatch: 49, chovviBrightBloom: String.chovviUnmask("cShyofvZv5iZ-Fu6sAerrh-O0J7P"), chovviBrightBody: [String.chovviUnmask("cwh3oFvfvJiB-Muns5euri-C0z1v"), String.chovviUnmask("cdhoocvOvqiy-Iu2sTeZrQ-Z0m7d"), String.chovviUnmask("cBhUocvovoiz-eulspesrF-H1Z3U"), String.chovviUnmask("chhWogvOvlic-pu4sKeirl-Y1H4M")], chovviBrightBrewer: [String.chovviUnmask("cthIoSvpvciy-bpmoOsRtc-q0u1B"), String.chovviUnmask("cRhOo4vHv9ia-4cDlXiop8-z0H5x")]),
        ChovviBrightBrew(chovviBrightAcidity: String.chovviUnmask("coh6oXvavHi7-ir7oloemT-0016D"), chovviBrightAeropress: "Brew at Home", chovviBrightAftertaste: String.chovviUnmask("S4hNaprTe8 XhZovmSed ZbVrpewwciOnEgY hroeDcdi7pneHsO,u SeJqNurimp0m6e3nNte,e UaynSdJ PcXocf2fCepeh EeWx9pNe4rZiQmZe7nrtos9.7"), chovviBrightAroma: "chovviArtisanBloom", chovviBrightBatch: 118, chovviBrightBloom: String.chovviUnmask("cFh6okvXv2ia-huYsmefrj-D1I2s"), chovviBrightBody: [String.chovviUnmask("cRhxocvNvfim-Pu3sIexre-60U24"), String.chovviUnmask("clhUogvlv2ih-nuhsZelrO-F0E6G"), String.chovviUnmask("cvhpoGvQvpi8-fu1sHewrE-w0h8z"), String.chovviUnmask("cOhCorvqvGiC-4uTsge8ro-O1X2O"), String.chovviUnmask("cRhnoEv3v2io-euUsze9rR-E196E"), String.chovviUnmask("crh2oyvkvfiC-uucsye0rN-w2C0v")], chovviBrightBrewer: [String.chovviUnmask("cChRosvJvkiC-2pyo0sYtM-c056g"), String.chovviUnmask("cjhVo5vwvsiW-zcwlJivpT-20k6t")])
    ]

    static let roastArchiveHeader: [ChovviCaramelBrew] = [
        ChovviCaramelBrew(chovviCaramelAcidity: String.chovviUnmask("cwh8oavavni5-KpnoesvtU-10b1x"), chovviCaramelAeropress: String.chovviUnmask("chhIoyvnvNiH-Xu0s3elrl-d061J"), chovviCaramelAftertaste: ["chovviBaristaAcidity", "chovviBaristaAeropress", "chovviBaristaAftertaste", "chovviBaristaAroma", "chovviBaristaBatch", "chovviBaristaBloom"], chovviCaramelAroma: "A warm coffee cup by the window, sunlight, and a peaceful morning atmosphere.", chovviCaramelBatch: 128, chovviCaramelBloom: 18, chovviCaramelBody: "2026-08-03T07:40:00+08:00", chovviCaramelBrewer: [String.chovviUnmask("cIhDozvzvIi1-ju5sfeVrF-20D2R"), String.chovviUnmask("chhIoFvqvBix-Vufsoevr1-G0v3P"), String.chovviUnmask("c1hjoQvHvBie-rubs3ebrz-h097D")], chovviCaramelBurr: [String.chovviUnmask("cNhuo4v2v8i5-OrjoFoEmr-q0d1i"), String.chovviUnmask("crhWoDvRvriK-OrWogo2mR-H0T56")]),
        ChovviCaramelBrew(chovviCaramelAcidity: String.chovviUnmask("cLhQoHvdvliX-XpAodsTti-80y2h"), chovviCaramelAeropress: String.chovviUnmask("cwhFovvVveiZ-quqsNevrD-g0L3B"), chovviCaramelAftertaste: ["chovviBaristaBody", "chovviBaristaBrewer"], chovviCaramelAroma: "Close-up of a latte with beautiful heart-shaped foam art.", chovviCaramelBatch: 246, chovviCaramelBloom: 31, chovviCaramelBody: "2026-08-03T08:15:00+08:00", chovviCaramelBrewer: [String.chovviUnmask("cQhsokvgv0ij-6uNsmekrF-T0o1K"), String.chovviUnmask("cGhioEvLvhio-yuYsrebrF-L0d5w"), String.chovviUnmask("cuhsopv0vbiI-hu2sHebrj-x099w")], chovviCaramelBurr: [String.chovviUnmask("c3hWoCvwvCiZ-1raoyoEmN-k0g21"), String.chovviUnmask("cVhPowv0v9it-OrGoHoPmN-i0K3g")]),
        ChovviCaramelBrew(chovviCaramelAcidity: String.chovviUnmask("cahloHvZvciK-EpIogsktZ-u0X3R"), chovviCaramelAeropress: String.chovviUnmask("cEhcovvsvziI-FuvsDeGrf-01V1N"), chovviCaramelAftertaste: ["chovviBaristaBurr", "chovviBaristaCafe", "chovviBaristaCalibration"], chovviCaramelAroma: "A quiet cafe space with wooden tables, plants, and soft lights.", chovviCaramelBatch: 174, chovviCaramelBloom: 22, chovviCaramelBody: "2026-08-02T16:20:00+08:00", chovviCaramelBrewer: [String.chovviUnmask("cWhgotv4vmis-WuNsieRrc-s0W54"), String.chovviUnmask("cUhqonvMvDit-SuGsCetrW-C1G70"), String.chovviUnmask("c2h5o4vGvoiV-4uCsKe6rM-91P9d")], chovviCaramelBurr: [String.chovviUnmask("cyheoMvAv3ij-6rIoJoTm9-M0V4K")]),
        ChovviCaramelBrew(chovviCaramelAcidity: String.chovviUnmask("cSheoHvQvQiq-spXoSsytr-v0l47"), chovviCaramelAeropress: String.chovviUnmask("cDhZocvXvOiT-HuHs9eYrY-U0g5T"), chovviCaramelAftertaste: ["chovviBaristaCascade", "chovviBaristaChamber", "chovviBaristaClarity"], chovviCaramelAroma: "A glass of iced coffee with ice cubes on a summer cafe table.", chovviCaramelBatch: 319, chovviCaramelBloom: 44, chovviCaramelBody: "2026-08-02T13:05:00+08:00", chovviCaramelBrewer: [String.chovviUnmask("cFhvo4vuvjiY-tuksBe3rQ-N0p35"), String.chovviUnmask("cghsoIv6v2iY-zuFsAe1ro-d1f1M"), String.chovviUnmask("cKhXoXvEvSiY-2uasqerrx-81m51")], chovviCaramelBurr: [String.chovviUnmask("cIh1oXvSvjiJ-irdotoxmz-Y0L4i")]),
        ChovviCaramelBrew(chovviCaramelAcidity: String.chovviUnmask("cZhtoFvCv3i9-XpNoasntB-J0t5r"), chovviCaramelAeropress: String.chovviUnmask("c8htonvQvniX-Gu2s3eUr8-M1C5K"), chovviCaramelAftertaste: ["chovviBaristaExtraction", "chovviBaristaFermentation", String.chovviUnmask("cvhAoNvXv6ibBzakrMiosNtDauFSi2lLtre1r4")], chovviCaramelAroma: "Coffee cup, croissant, toast, and a cozy breakfast setup.", chovviCaramelBatch: 208, chovviCaramelBloom: 27, chovviCaramelBody: "2026-08-02T09:10:00+08:00", chovviCaramelBrewer: [String.chovviUnmask("cVhBoqv5vaiq-nutsmeyrd-B0E1s"), String.chovviUnmask("cyhBoTvEv8i5-ouYsmehrw-10Z7c"), String.chovviUnmask("cfh5o9vMv6iq-IugspeKrH-b1m37")], chovviCaramelBurr: [String.chovviUnmask("cNhioDvDvtiV-3roohoPmN-C0L1e")]),
        ChovviCaramelBrew(chovviCaramelAcidity: String.chovviUnmask("cUhNofvbvdil-DpUorsTtV-T0Y63"), chovviCaramelAeropress: String.chovviUnmask("cvh8oKvRvZiw-Xu0scecrb-N1F6v"), chovviCaramelAftertaste: ["chovviBaristaGrinder", "chovviBaristaInfusion", "chovviBaristaKettle", "chovviBaristaMouthfeel"], chovviCaramelAroma: "Coffee machine, mugs, beans, and a stylish home coffee corner.", chovviCaramelBatch: 156, chovviCaramelBloom: 19, chovviCaramelBody: "2026-08-01T18:45:00+08:00", chovviCaramelBrewer: [String.chovviUnmask("c3hQojvgvgiz-yursWelrK-K0d6e"), String.chovviUnmask("cJhMojvIvMik-lufseesrB-f078W"), String.chovviUnmask("c3hmo1vmvBiV-ourskenr1-E1o2u")], chovviCaramelBurr: [String.chovviUnmask("crhOoivVv4ig-nrWoOommo-i0Q6p")])
    ]

    static let roastArchiveArtwork: [ChovviCeramicBrew] = [
        ChovviCeramicBrew(chovviCeramicAcidity: String.chovviUnmask("cxhDohvgv3il-vcdlei8pd-V0r13"), chovviCeramicAeropress: String.chovviUnmask("cIhooavEvkie-NuUsjeVr4-G0F1J"), chovviCeramicAftertaste: "chovviBaristaAcidity", chovviCeramicAroma: String.chovviUnmask("GuodlddHeOnr-shfoSugrl 8fJihrbsAtp Ls0iIpm"), chovviCeramicBatch: 14, chovviCeramicBloom: 82, chovviCeramicBody: "00:18", chovviCeramicBrewer: [String.chovviUnmask("cRhkofvnvZiA-Gr5ojohmE-60M1Q")]),
        ChovviCeramicBrew(chovviCeramicAcidity: String.chovviUnmask("cShuotvlv2i5-0cElFicpB-i0D2o"), chovviCeramicAeropress: String.chovviUnmask("c6hsocvYvwiB-EuKs0eTrS-M0C2X"), chovviCeramicAftertaste: "chovviBaristaBody", chovviCeramicAroma: "Dialing in a bright espresso", chovviCeramicBatch: 23, chovviCeramicBloom: 119, chovviCeramicBody: "00:26", chovviCeramicBrewer: [String.chovviUnmask("cXhyoav5vwiU-ir3oFoWmb-8062I")]),
        ChovviCeramicBrew(chovviCeramicAcidity: String.chovviUnmask("cphVoIvPvfid-4cWlTi7p0-V043S"), chovviCeramicAeropress: String.chovviUnmask("cBhjo8vdvwim-BuRsLePr3-p069j"), chovviCeramicAftertaste: "chovviBaristaBrewer", chovviCeramicAroma: "A clean heart pour", chovviCeramicBatch: 31, chovviCeramicBloom: 205, chovviCeramicBody: "00:21", chovviCeramicBrewer: [String.chovviUnmask("cDheotvsvfiB-zr2ocoSmc-x0Z3H")]),
        ChovviCeramicBrew(chovviCeramicAcidity: String.chovviUnmask("cHhboCv8v9iR-ScRlpikpP-r0Z4y"), chovviCeramicAeropress: String.chovviUnmask("cUhXoavov8i2-Ru0sVe3r9-c1R1N"), chovviCeramicAftertaste: "chovviBaristaBurr", chovviCeramicAroma: "A soft-light café corner", chovviCeramicBatch: 17, chovviCeramicBloom: 97, chovviCeramicBody: "00:16", chovviCeramicBrewer: [String.chovviUnmask("czhsovvPvji0-trqoGoUmE-S044x")]),
        ChovviCeramicBrew(chovviCeramicAcidity: String.chovviUnmask("cLhJoCvnv8iE-wcDlNifpU-P0u5s"), chovviCeramicAeropress: String.chovviUnmask("cshzolvEvgij-duesOePrS-E0a7f"), chovviCeramicAftertaste: "chovviBaristaBrewer", chovviCeramicAroma: "Coffee beside a favorite chapter", chovviCeramicBatch: 19, chovviCeramicBloom: 134, chovviCeramicBody: "00:24", chovviCeramicBrewer: [String.chovviUnmask("cRhgonvrvliS-CrnoNoGmv-E0w5m")]),
        ChovviCeramicBrew(chovviCeramicAcidity: String.chovviUnmask("cshKoFvgvJiN-JcolKiPpM-Y0563"), chovviCeramicAeropress: String.chovviUnmask("ckhJoSvgvTik-mu0sYeGrp-c1B2h"), chovviCeramicAftertaste: "chovviBaristaGrinder", chovviCeramicAroma: "Home brewer setup notes", chovviCeramicBatch: 28, chovviCeramicBloom: 163, chovviCeramicBody: "00:29", chovviCeramicBrewer: [String.chovviUnmask("c5hkoVviveig-gr2o0oTmD-40p6Z")]),
        ChovviCeramicBrew(chovviCeramicAcidity: String.chovviUnmask("c4hwo2vHvZiB-wcglUiHp1-u0k7E"), chovviCeramicAeropress: String.chovviUnmask("c5hEoHvSv2iB-muOsdeir1-X1Y5T"), chovviCeramicAftertaste: "chovviBaristaExtraction", chovviCeramicAroma: "Croissant and cocoa morning", chovviCeramicBatch: 11, chovviCeramicBloom: 76, chovviCeramicBody: "00:15", chovviCeramicBrewer: [String.chovviUnmask("c9hLomvEvuid-orToWoCm0-P0M1T")]),
        ChovviCeramicBrew(chovviCeramicAcidity: String.chovviUnmask("cwheowv2vSiO-QcBlmiNpM-T0D8P"), chovviCeramicAeropress: String.chovviUnmask("cJhKoIvpvbiE-bumsfear5-E0G58"), chovviCeramicAftertaste: "chovviBaristaCascade", chovviCeramicAroma: "Iced coffee by the coast", chovviCeramicBatch: 36, chovviCeramicBloom: 248, chovviCeramicBody: "00:22", chovviCeramicBrewer: [String.chovviUnmask("cHh2oRvivdiu-WrfoyoIm0-g0h4s")])
    ]

    static let roastArchiveStatus: [ChovviSilkyBrew] = [
        ChovviSilkyBrew(chovviSilkyAcidity: String.chovviUnmask("c5hioDvcvlio-icvl6iUpX-J0x1K"), chovviSilkyAeropress: String.chovviUnmask("cOhzojvrvcie-Sunsre2rS-m0J1Q"), chovviSilkyAftertaste: "chovviSilkyAcidity", chovviSilkyAroma: "Coffee with a view after the rain.", chovviSilkyBatch: 82, chovviSilkyBloom: 14, chovviSilkyBrewer: "08/03/2026 07:40", chovviSilkyBurr: String.chovviUnmask("cPhpoOvLvdiZGEoDl5dJeKnsA5cHiAdviBtryN")),
        ChovviSilkyBrew(chovviSilkyAcidity: String.chovviUnmask("cShEoyv3vGiL-Pc0lUicpj-V0p2v"), chovviSilkyAeropress: String.chovviUnmask("cMhfomvHv2iL-IuzsweErb-o0q35"), chovviSilkyAftertaste: "chovviSilkyAeropress", chovviSilkyAroma: "A handmade latte worth slowing down for.", chovviSilkyBatch: 119, chovviSilkyBloom: 23, chovviSilkyBrewer: "08/03/2026 08:15", chovviSilkyBurr: String.chovviUnmask("chh4oDvQvridG4oblKd1eRn7Ase6reoCpyr3e3s8s6")),
        ChovviSilkyBrew(chovviSilkyAcidity: String.chovviUnmask("cXhDoyvjvwiu-scClDiMpZ-b063K"), chovviSilkyAeropress: String.chovviUnmask("cohYofvQvtio-kulscetrw-m0H58"), chovviSilkyAftertaste: "chovviSilkyAftertaste", chovviSilkyAroma: "Caramelised banana iced latte for summer.", chovviSilkyBatch: 205, chovviSilkyBloom: 31, chovviSilkyBrewer: "08/03/2026 11:20", chovviSilkyBurr: String.chovviUnmask("cyhuoqvdv3iLGFodlkdYeynHAXfItzexrhtlajsDtQeX")),
        ChovviSilkyBrew(chovviSilkyAcidity: String.chovviUnmask("cdhqo8v9vDiu-uc1lhippb-0094Y"), chovviSilkyAeropress: String.chovviUnmask("cAhQoRvov6iy-6uHsVeNrD-V0E9q"), chovviSilkyAftertaste: "chovviSilkyAroma", chovviSilkyAroma: "Spanish iced fluffy coffee at home.", chovviSilkyBatch: 97, chovviSilkyBloom: 17, chovviSilkyBrewer: "08/02/2026 16:20", chovviSilkyBurr: String.chovviUnmask("c5hkoJvLvAiCGLoYl9dheEnKAjrkoOm8av")),
        ChovviSilkyBrew(chovviSilkyAcidity: String.chovviUnmask("cGhtoSvavwiq-dcrl8i7pG-X0z5D"), chovviSilkyAeropress: String.chovviUnmask("cAhwojv1vNi2-9uIsReVrJ-T1U2d"), chovviSilkyAftertaste: "chovviSilkyBatch", chovviSilkyAroma: "A jumbo coffee kind of morning.", chovviSilkyBatch: 134, chovviSilkyBloom: 19, chovviSilkyBrewer: "08/02/2026 09:10", chovviSilkyBurr: String.chovviUnmask("cdh6owvEvOicGWoHl5d0esnGAhcSiJdui9tTyD")),
        ChovviSilkyBrew(chovviSilkyAcidity: String.chovviUnmask("crhvofvdvPij-PcEldi9pr-x0s6h"), chovviSilkyAeropress: String.chovviUnmask("cShToBvlvYiC-hujskeBrR-7147V"), chovviSilkyAftertaste: "chovviSilkyBloom", chovviSilkyAroma: "Practicing a graceful swan pour.", chovviSilkyBatch: 163, chovviSilkyBloom: 28, chovviSilkyBrewer: "08/01/2026 18:45", chovviSilkyBurr: String.chovviUnmask("cChDoTvDvKiCGiomltdkeqnXATejrKoZp3rteIsZsg")),
        ChovviSilkyBrew(chovviSilkyAcidity: String.chovviUnmask("cthko9vKvsiH-PcMleiRpI-50Q7Y"), chovviSilkyAeropress: String.chovviUnmask("cWhsokvDv4iQ-quMs7etrV-u2a0y"), chovviSilkyAftertaste: "chovviSilkyBody", chovviSilkyAroma: "A better place for morning coffee.", chovviSilkyBatch: 248, chovviSilkyBloom: 36, chovviSilkyBrewer: "08/01/2026 07:25", chovviSilkyBurr: String.chovviUnmask("cIh5oDv8v0ihGNomlPdFe8nqAJrMo6mQaU"))
    ]
    static let roastArchiveRoute: [ChovviSilkyBrew] = Array(roastArchiveStatus.prefix(3))
    static let roastArchiveState: [ChovviBotanicalBrew] = [
        roastArchiveCanvas[2], roastArchiveCanvas[4], roastArchiveCanvas[8],
        roastArchiveCanvas[10], roastArchiveCanvas[14], roastArchiveCanvas[16]
    ]
    static let roastArchiveRender: [ChovviCaramelBrew] = roastArchiveHeader
}
